In [1]:
%%file arraytimeseries.py
import numpy as np
class ArrayTimeSeries(): 
    """
    An class that takes a sequence of integers or floats as input
    
    Parameters
    ----------
    data : any finite numeric sequence
   
    Returns
    -------
    len(TimeSeries): int
        an integer representing the length of the time series
    Timeseries[position:int]: number
        returns the value of the TimeSeries at position
    Timeseries[position:int] = value:int/float
        set value of TimeSeries at position to be value
    __str__ / __repr__:
        when printing TimeSeries, if the total length of the Timeseries is greater than 10
        the result shows the first ten elements and its total length, else it prints the 
        whole Timeseries
        
    Examples
    --------
    >>> threes = ArrayTimeSeries(range(0,10000,3))
    >>> zeroes = ArrayTimeSeries(range(0,10,3))
    >>> len(threes)
    3334
    >>> threes[10]
    30
    >>> threes[10]=10
    >>> threes[10]
    10
    >>> print(zeroes)
    [0 3 6 9]
    >>> print(threes)
    [ 3  6  9 12 15 18 21 24 27...,length=3334]
        
    Notes
    -----
    PRE: `data` is numeric
    
    """
    def __init__(self,data):
        self.data=np.array(data)
        self.len=len(data)
    def __len__(self):
        return len(self.data)
    def __getitem__(self, position):
        return self.data[position]
    def __setitem__(self,position,value):
        self.data[position]=value
    def __str__(self):
        if self.len>10:
            return '[{}...,length={}]'.format(str(self.data[1:10])[1:-1], self.len)
        return '{}'.format(self.data)
    def __repr__(self):
        if self.len>10:
            return '[{}...,length={}]'.format(str(self.data[1:10])[1:-1], self.len)
        return '{}'.format(self.data)
    

Overwriting arraytimeseries.py


In [6]:
from arraytimeseries import ArrayTimeSeries
a=ArrayTimeSeries([1,2,3])
a[0:3]

array([1, 2, 3])

In [4]:
from pydoc import doc as pydoc
from doctest import run_docstring_examples as dtest
dtest(ArrayTimeSeries, globals(), verbose=True)

Finding tests in NoName
Trying:
    threes = ArrayTimeSeries(range(0,10000,3))
Expecting nothing
ok
Trying:
    zeroes = ArrayTimeSeries(range(0,10,3))
Expecting nothing
ok
Trying:
    len(threes)
Expecting:
    3334
ok
Trying:
    threes[10]
Expecting:
    30
ok
Trying:
    threes[10]=10
Expecting nothing
ok
Trying:
    threes[10]
Expecting:
    10
ok
Trying:
    print(zeroes)
Expecting:
    [0 3 6 9]
ok
Trying:
    print(threes)
Expecting:
    [ 3  6  9 12 15 18 21 24 27...,length=3334]
ok


In [ ]:
#todo: make a copy instead????
from doctest import run_docstring_examples as dtest
import numbers
import reprlib
class LL:
    """
    >>> A = LL()  
    >>> A[0]
    Traceback (most recent call last):
        ...
    IndexError: trying to index an empty LL
    >>> A.insert_front(1)
    >>> A[0]
    1
    >>> A.insert_back(2)
    >>> A[1]
    2
    >>> A
    LL([1,...])
    >>> myll = LL.from_components([1,2])
    >>> myll[1]
    1
    >>> len(myll)
    2
    >>> myll[2]
    Traceback (most recent call last):
        ...
    IndexError: LL index out of range
    >>> myll[0:1]
    Traceback (most recent call last):
        ...
    TypeError: LL indices must be integers
    """
    @classmethod
    def from_components(cls, components):
        inst = cls(components[0])
        for c in components[1:]:
            inst.insert_front(c)
        return inst
        
    def __init__(self, head=None):
        if head is None:
            self._headNode = None
        else:
            self._headNode = [head, None]
            
    def insert_front(self, element):
        new_node = [element, None]
        new_node[1] = self._headNode
        self._headNode = new_node
        
    def insert_back(self, element):
        new_node = [element, None]
        curr_ptr = self._headNode
        while curr_ptr[1] is not None:
            curr_ptr = curr_ptr[1]
        curr_ptr[1]= new_node
        
    def __repr__(self):
        class_name = type(self).__name__
        if len(self)==0:
            components=""
        else:
            components = reprlib.repr(self[0])
        return '{}([{},...])'.format(class_name,components)


    def __len__(self):
        curr_ptr = self._headNode
        count = 0
        if curr_ptr==None:
            return 0
        while 1:
            count = count + 1
            if curr_ptr[1] is None:
                break
            curr_ptr = curr_ptr[1]
        return count    
    
    def __getitem__(self, index):
        class_name = type(self).__name__
        if isinstance(index, numbers.Integral): 
            curr_ptr = self._headNode
            if curr_ptr==None:
                msg = 'trying to index an empty {class_name}' 
                raise IndexError(msg.format(class_name=class_name))
            next_ptr = self._headNode[1]
            count = 0
            while 1:
                if index == count:
                    return curr_ptr[0]
                if curr_ptr[1] is None:
                    msg = '{class_name} index out of range' 
                    raise IndexError(msg.format(class_name=class_name))       
                count += 1
                curr_ptr = curr_ptr[1]
        else:
            msg = '{class_name} indices must be integers' 
            raise TypeError(msg.format(class_name=class_name))